# Generated by Django 2.2 on 2020-05-25 00:36

from django.db import migrations
import gallery.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to=gallery.models.get_gallery_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=gallery.models.get_image_path),
        ),
    ]
